lang: en-GB
title: SCRIPT REPORT
email: aaron.beecham@intellipharm.com.au
logo: /images/icon-new.png
description: Intellipharm script monthly data report.
url: "https://aaronbeecham.github.io/" 

search: true

markdown: kramdown
remote_theme: "mmistakes/jekyll-theme-basically-basic"
plugins:
  - jekyll-feed

author:
  name: Aaron Beecham
  picture: /images/icon-new.png